"""Pets, Messages, BestFriends, update Users

Revision ID: d57395948c9f
Revises: ffdc0a98111c
Create Date: 2021-02-22 17:08:10.642191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57395948c9f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senderId', sa.Integer(), nullable=False),
    sa.Column('receiverId', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiverId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('petType', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('imageURL', sa.String(length=2083), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('social', sa.Integer(), nullable=False),
    sa.Column('behaved', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('env', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('best_friends',
    sa.Column('frmBFPetId', sa.Integer(), nullable=False),
    sa.Column('toBFPetId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frmBFPetId'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['toBFPetId'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('frmBFPetId', 'toBFPetId')
    )
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('stateAbbr', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stateAbbr')
    op.drop_column('users', 'city')
    op.drop_table('best_friends')
    op.drop_table('pets')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
